# Generated by Django 5.2.4 on 2025-07-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_type',
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(default='dQw4w9WgXcQ', max_length=20),
        ),
    ]
